platformbuilders/fluid-react

- package.json
- src/components/Radio/__test__/__snapshots__/radio.spec.tsx.snap
- src/types/Button.ts
Estava ocorrendo um erro ao usar o botão, onde estava sendo obrigatório passar o tema como prop. Agora não é mais necessário.
| -----Figma----- | -Implementação- |
| :-------------: | :-------------: |
|  |  |
> fix(button): fix button type definition

- src/components/LazyWrapper/index.stories.jsx
- src/components/LazyWrapper/index.tsx
- src/components/LazyWrapper/lazy-wrapper.md
- src/components/LazyWrapper/styles.ts
- src/components/index.ts
- src/types/LazyWrapper.ts
- src/types/index.ts
Criei um componente de wrapper com o intuito de tratar os loading dentro de cenários como requisições para api, nesse caso, o código seria transformado disso:
```tsx
{loading ? <Loading /> : <Component />}
```
Para isso:
```tsx
<LazyWrapper loading={loading}>
<Component />
</LazyWrapper>
```
Removendo assim grandes códigos com ternários ou até mesmo os components de `If` da própria builders.
O `LazyWrapper` é totalmente customizável, podendo alterar o indicador (passando um element), cor do indicador, tamanho do indicador e o único parâmetro obrigatório é o `loading`.
Criei ele baseado no que o nosso `If` trata aqui dentro também, portanto acredito que esse tipo de component pode agregar muito valor e remover trechos de códigos que são necessários mas não tão elegantes.
Criei a …
> feat: create lazy wrapper component

- package.json
> chore: update lib version

- src/components/Select/index.tsx
Adicionado ID para o component de Select.
- Adicionado ID para o botão principal do Select.
- Adicionado ID para as opções do select.
- [ x ] Refactor (mudança non-breaking que melhora o código ou débito técnico)
> chore: added id to SelectInput component

- .gitignore
- .husky/pre-commit
- src/components/Select/index.stories.jsx
| -----Figma----- | -Implementação- |
| :-------------: | :-------------: |
|  |  |
> chore(codewall): add configuration and pre commit hook

- src/components/TextInput/TextInputMask/index.tsx
Removido propriedades desnecessárias passadas pro input do material no TextInputMask
| -----Figma----- | -Implementação- |
| :-------------: | :-------------: |
|  |  |
> Fix TextInputMask remove function events in children

- package.json
- src/components/Button/index.tsx
- src/components/Button/styles.tsx
- yarn.lock
- removido props não utilizadas com nomes privados
> fix(warnings): button

- src/components/Switch/__tests__/__snapshots__/switch.test.tsx.snap
- src/components/Switch/__tests__/switch.test.tsx
Adicionado test de snapshot ao componente switch
> Switch Test

- .github/workflows/check.yml
> Usando check compartilhado

- .github/workflows/publish.yml
Adicionado action compartilhada de publish
> Adicionado publish workflow

- package.json
- src/components/Avatar/__tests__/__snapshots__/avatar.spec.tsx.snap
- src/components/Avatar/__tests__/avatar.spec.tsx
- src/components/Avatar/index.tsx
- src/components/Avatar/styles.ts
- yarn.lock
Criado componente `Avatar`
[avatar.webm](https://github.com/platformbuilders/fluid-react/assets/7242605/afc60550-99f9-42b2-baa0-bb1e2fccdd75)
> Create avatar component

- .github/workflows/check.yml
- src/components/Checkbox/__tests__/__snapshots__/checkbox.spec.tsx.snap
- src/components/Checkbox/index.tsx
- src/components/Checkbox/styles.tsx
- yarn.lock
Criado componente `checkbox`
https://github.com/platformbuilders/fluid-react/assets/37779345/7279780d-0e47-45d6-99c8-2eb15622f0e6
> Created new checkbox component

- src/components/Button/__tests__/__snapshots__/button.spec.tsx.snap
- src/components/FormError/__tests__/__snapshots__/formError.spec.tsx.snap
- src/components/Typography/__tests__/__snapshots__/typography.spec.tsx.snap
- src/components/Typography/index.tsx
- src/components/Typography/styles.tsx
- src/components/Typography/typography.md
- src/types/Typography.ts
- yarn.lock
- Adicionada propriedade `as` juntamente com a tipagam e exemplo de uso
> Refactor typography

- src/components/Button/__tests__/__snapshots__/button.spec.tsx.snap
- src/components/Button/styles.tsx
Adicionado botão sem material UI
> Adicionado botão sem material UI

- jest.config.js
- src/components/Switch/index.tsx
- src/components/Switch/styles.ts
Adicionado componente `Switch` sem utilização do `material ui`
[switch.webm](https://github.com/platformbuilders/fluid-react/assets/7242605/3871fb4e-6771-4b98-8bc8-f1ad1c08c17a)
> Switch without material styles

- package.json
- src/components/Select/__test__/__snapshots__/select.test.tsx.snap
- src/components/Select/__test__/select.test.tsx
- src/components/Select/index.tsx
- src/components/Select/styles.tsx
- yarn.lock
Criado componente `select` utilizando a lib `radix-ui`
[select.webm](https://github.com/platformbuilders/fluid-react/assets/7242605/851d7786-512c-4d2d-ba77-c95becb951d7)
> Add select component with radix-ui

- package.json
- src/components/LoadingIndicator/LoadingIndicator.test.tsx
- vitest.config.ts
- yarn.lock
Configurado coverage minimo utilizando `vitest`
> Configure minimum converage

- package.json
- src/components/TextInput/styles.tsx
Correção da cor do label e borda do input, agora está setando a cor do tema
- [] Testado no Yalc
> Correção da cor do text input

- package.json
- src/components/TextInput/index.tsx
Adicionado {...rest} ao text input mask
> Style Text Input mask

- package.json
- src/components/Button/index.tsx
- src/components/Button/styles.tsx
- src/components/Button/types.ts
Correção do camel case dos props do botão
> fix button variant camel case

- .firebaserc
- .github/workflows/storybook.publish.yml
- firebase.json
- yarn.lock
Hospedado Storybook no Firebase: https://fluid-react.web.app e criado CI
> feat: hosting firebase

- src/components/TextInput/styles.tsx
Correção de espaçamento e altura do TextInput
> Correção do textinput

- src/components/Radio/index.tsx
- src/components/Radio/radio.stories.tsx
- src/components/Radio/styles.ts
- src/components/RadioGroup/index.tsx
- src/components/RadioGroup/radio-group.stories.tsx
- src/components/RadioGroup/styles.ts
- yarn.lock
- Refatoração do componente Radio para se adaptar a nova UI proposta.
- Criação do componente RadioGroup para facilitar o desenvolvimento de novos projetos.
> feat: refactor radio button and implement radioGroup

- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/index.tsx
- src/components/Checkbox/styles.tsx
Foi adicionado uma variante "primary" no componente checkbox.
> refactor: add variant in checkbox
